// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using ECommerce.Beganit.AdminPanel.Data;
using ECommerce.Beganit.AdminPanel.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace ECommerce.Beganit.AdminPanel.Data.Configurations
{
    public partial class OrderStatusHistoryConfiguration : IEntityTypeConfiguration<OrderStatusHistory>
    {
        public void Configure(EntityTypeBuilder<OrderStatusHistory> entity)
        {
            entity.HasKey(e => e.Id).HasName("PK__OrderSta__3214EC07525C5F53");

            entity.ToTable("OrderStatusHistory");

            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(getdate())");

            entity.HasOne(d => d.Order).WithMany(p => p.OrderStatusHistories)
                .HasForeignKey(d => d.OrderId)
                .HasConstraintName("FK__OrderStat__Order__3B40CD36");

            entity.HasOne(d => d.OrderStatus).WithMany(p => p.OrderStatusHistories)
                .HasForeignKey(d => d.OrderStatusId)
                .HasConstraintName("FK__OrderStat__Order__3C34F16F");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<OrderStatusHistory> entity);
    }
}
