// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using ECommerce.Beganit.AdminPanel.Data;
using ECommerce.Beganit.AdminPanel.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace ECommerce.Beganit.AdminPanel.Data.Configurations
{
    public partial class ProductBundleItemConfiguration : IEntityTypeConfiguration<ProductBundleItem>
    {
        public void Configure(EntityTypeBuilder<ProductBundleItem> entity)
        {
            entity.HasKey(e => new { e.BundleId, e.ProductId }).HasName("PK__ProductB__8940F83D57DA28BF");

            entity.Property(e => e.Quantity).HasDefaultValue(1);

            entity.HasOne(d => d.Bundle).WithMany(p => p.ProductBundleItems)
                .HasForeignKey(d => d.BundleId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__ProductBu__Bundl__3E1D39E1");

            entity.HasOne(d => d.Product).WithMany(p => p.ProductBundleItems)
                .HasForeignKey(d => d.ProductId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__ProductBu__Produ__3F115E1A");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<ProductBundleItem> entity);
    }
}
