// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using ECommerce.Beganit.AdminPanel.Data;
using ECommerce.Beganit.AdminPanel.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace ECommerce.Beganit.AdminPanel.Data.Configurations
{
    public partial class RelatedProductConfiguration : IEntityTypeConfiguration<RelatedProduct>
    {
        public void Configure(EntityTypeBuilder<RelatedProduct> entity)
        {
            entity.HasKey(e => new { e.ProductId, e.RelatedProductId }).HasName("PK__RelatedP__4184C85E75AEC7A5");

            entity.Property(e => e.RelationType).HasMaxLength(20);

            entity.HasOne(d => d.Product).WithMany(p => p.RelatedProductProducts)
                .HasForeignKey(d => d.ProductId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__RelatedPr__Produ__45BE5BA9");

            entity.HasOne(d => d.RelatedProductNavigation).WithMany(p => p.RelatedProductRelatedProductNavigations)
                .HasForeignKey(d => d.RelatedProductId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__RelatedPr__Relat__46B27FE2");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<RelatedProduct> entity);
    }
}
