// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using ECommerce.Beganit.AdminPanel.Data;
using ECommerce.Beganit.AdminPanel.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace ECommerce.Beganit.AdminPanel.Data.Configurations
{
    public partial class WishlistNotificationConfiguration : IEntityTypeConfiguration<WishlistNotification>
    {
        public void Configure(EntityTypeBuilder<WishlistNotification> entity)
        {
            entity.HasKey(e => e.Id).HasName("PK__Wishlist__3214EC07D32FA9BC");

            entity.Property(e => e.CreatedDate)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.IsRead).HasDefaultValue(false);
            entity.Property(e => e.NotificationType)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.WishlistItemId).HasColumnName("WishlistItemID");

            entity.HasOne(d => d.WishlistItem).WithMany(p => p.WishlistNotifications)
                .HasForeignKey(d => d.WishlistItemId)
                .HasConstraintName("FK_WishlistNotifications_WishlistItems");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<WishlistNotification> entity);
    }
}
