// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using ECommerce.Beganit.AdminPanel.Data;
using ECommerce.Beganit.AdminPanel.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace ECommerce.Beganit.AdminPanel.Data.Configurations
{
    public partial class WishlistShareConfiguration : IEntityTypeConfiguration<WishlistShare>
    {
        public void Configure(EntityTypeBuilder<WishlistShare> entity)
        {
            entity.HasKey(e => e.Id).HasName("PK__Wishlist__3214EC079736F4FB");

            entity.Property(e => e.ExpiryDate).HasColumnType("datetime");
            entity.Property(e => e.IsEditable).HasDefaultValue(false);
            entity.Property(e => e.RecipientEmail)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.SharedDate)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.SharingCode).HasDefaultValueSql("(newid())");

            entity.HasOne(d => d.Wishlist).WithMany(p => p.WishlistShares)
                .HasForeignKey(d => d.WishlistId)
                .HasConstraintName("FK_WishlistShares_Wishlists");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<WishlistShare> entity);
    }
}
