// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ECommerce.Beganit.AdminPanel.Models;

public partial class AuditLog
{
    public int Id { get; set; }

    public int? UserId { get; set; }

    public string UserType { get; set; }

    public string Action { get; set; }

    public string EntityName { get; set; }

    public int? EntityId { get; set; }

    public string OldValues { get; set; }

    public string NewValues { get; set; }

    public DateTime? CreatedAt { get; set; }
}