// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ECommerce.Beganit.AdminPanel.Models;

public partial class OrderStatusHistory
{
    public int Id { get; set; }

    public int? OrderId { get; set; }

    public int? OrderStatusId { get; set; }

    public DateTime? CreatedAt { get; set; }

    public int? CreatedBy { get; set; }

    public virtual Order Order { get; set; }

    public virtual OrderStatus OrderStatus { get; set; }
}