// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ECommerce.Beganit.AdminPanel.Models;

public partial class ProductVariantAttribute
{
    public int VariantId { get; set; }

    public string AttributeName { get; set; }

    public string AttributeValue { get; set; }

    public virtual ProductVariant Variant { get; set; }
}