// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ECommerce.Beganit.AdminPanel.Models;

public partial class Product
{
    public int Id { get; set; }

    public string Name { get; set; }

    public string Slug { get; set; }

    public string ShortDescription { get; set; }

    public string Description { get; set; }

    public string Sku { get; set; }

    public decimal RegularPrice { get; set; }

    public decimal? DiscountPrice { get; set; }

    public DateTime? DiscountStartDate { get; set; }

    public DateTime? DiscountEndDate { get; set; }

    public int? Quantity { get; set; }

    public decimal? Weight { get; set; }

    public decimal? Length { get; set; }

    public decimal? Width { get; set; }

    public decimal? Height { get; set; }

    public int? BrandId { get; set; }

    public bool IsActive { get; set; }

    public bool IsFeatured { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public int? CreatedBy { get; set; }

    public int? UpdatedBy { get; set; }

    public virtual Brand Brand { get; set; }

    public virtual ICollection<CartItem> CartItems { get; set; } = new List<CartItem>();

    public virtual ICollection<OrderItem> OrderItems { get; set; } = new List<OrderItem>();

    public virtual ICollection<ProductAttribute> ProductAttributes { get; set; } = new List<ProductAttribute>();

    public virtual ICollection<ProductBundleItem> ProductBundleItems { get; set; } = new List<ProductBundleItem>();

    public virtual ICollection<ProductImage> ProductImages { get; set; } = new List<ProductImage>();

    public virtual ICollection<ProductVariant> ProductVariants { get; set; } = new List<ProductVariant>();

    public virtual ICollection<RelatedProduct> RelatedProductProducts { get; set; } = new List<RelatedProduct>();

    public virtual ICollection<RelatedProduct> RelatedProductRelatedProductNavigations { get; set; } = new List<RelatedProduct>();

    public virtual ICollection<Review> Reviews { get; set; } = new List<Review>();

    public virtual ICollection<WishlistItem> WishlistItems { get; set; } = new List<WishlistItem>();

    public virtual ICollection<Category> Categories { get; set; } = new List<Category>();
}