// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ECommerce.Beganit.AdminPanel.Models;

public partial class RelatedProduct
{
    public int ProductId { get; set; }

    public int RelatedProductId { get; set; }

    public string RelationType { get; set; }

    public virtual Product Product { get; set; }

    public virtual Product RelatedProductNavigation { get; set; }
}