// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ECommerce.Beganit.AdminPanel.Models;

public partial class WishlistItem
{
    public int Id { get; set; }

    public int WishlistId { get; set; }

    public int ProductId { get; set; }

    public int? Quantity { get; set; }

    public DateTime? DateAdded { get; set; }

    public string Notes { get; set; }

    public int? Priority { get; set; }

    public virtual Product Product { get; set; }

    public virtual Wishlist Wishlist { get; set; }

    public virtual ICollection<WishlistNotification> WishlistNotifications { get; set; } = new List<WishlistNotification>();
}