// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ECommerce.Beganit.AdminPanel.Models;

public partial class WishlistNotification
{
    public int Id { get; set; }

    public int WishlistItemId { get; set; }

    public string NotificationType { get; set; }

    public bool? IsRead { get; set; }

    public DateTime? CreatedDate { get; set; }

    public virtual WishlistItem WishlistItem { get; set; }
}