// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ECommerce.Beganit.AdminPanel.Models;

public partial class WishlistShare
{
    public int Id { get; set; }

    public int WishlistId { get; set; }

    public string RecipientEmail { get; set; }

    public Guid? SharingCode { get; set; }

    public DateTime? SharedDate { get; set; }

    public DateTime? ExpiryDate { get; set; }

    public bool? IsEditable { get; set; }

    public virtual Wishlist Wishlist { get; set; }
}