// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ECommerce.Beganit.AdminPanel.Models;

public partial class Wishlist
{
    public int Id { get; set; }

    public int CustomerId { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public bool? IsPublic { get; set; }

    public DateTime? CreatedDate { get; set; }

    public DateTime? LastModifiedDate { get; set; }

    public virtual Customer Customer { get; set; }

    public virtual ICollection<WishlistItem> WishlistItems { get; set; } = new List<WishlistItem>();

    public virtual ICollection<WishlistShare> WishlistShares { get; set; } = new List<WishlistShare>();
}