// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using ECommerce.Beganit.AdminPanel.Data.Configurations;
using ECommerce.Beganit.AdminPanel.Models;
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using ECommerce.Beganit.AdminPanel.ViewModels;
#nullable disable

namespace ECommerce.Beganit.AdminPanel.Data;

public partial class ECommerceDBContext : IdentityDbContext
{
    public ECommerceDBContext(DbContextOptions<ECommerceDBContext> options)
        : base(options)
    {
    }

    public virtual DbSet<AuditLog> AuditLogs { get; set; }

    public virtual DbSet<Brand> Brands { get; set; }

    public virtual DbSet<Cart> Carts { get; set; }

    public virtual DbSet<CartItem> CartItems { get; set; }

    public virtual DbSet<Category> Categories { get; set; }

    public virtual DbSet<Customer> Customers { get; set; }

    public virtual DbSet<CustomerAddress> CustomerAddresses { get; set; }

    public virtual DbSet<Order> Orders { get; set; }

    public virtual DbSet<OrderItem> OrderItems { get; set; }

    public virtual DbSet<OrderStatus> OrderStatuses { get; set; }

    public virtual DbSet<OrderStatusHistory> OrderStatusHistories { get; set; }

    public virtual DbSet<PaymentMethod> PaymentMethods { get; set; }

    public virtual DbSet<PaymentStatus> PaymentStatuses { get; set; }

    public virtual DbSet<Permission> Permissions { get; set; }

    public virtual DbSet<Product> Products { get; set; }

    public virtual DbSet<ProductAttribute> ProductAttributes { get; set; }

    public virtual DbSet<ProductBundle> ProductBundles { get; set; }

    public virtual DbSet<ProductBundleItem> ProductBundleItems { get; set; }

    public virtual DbSet<ProductImage> ProductImages { get; set; }

    public virtual DbSet<ProductVariant> ProductVariants { get; set; }

    public virtual DbSet<ProductVariantAttribute> ProductVariantAttributes { get; set; }

    public virtual DbSet<RelatedProduct> RelatedProducts { get; set; }

    public virtual DbSet<Review> Reviews { get; set; }

    public virtual DbSet<Role> Roles { get; set; }

    public virtual DbSet<ShippingMethod> ShippingMethods { get; set; }

    public virtual DbSet<Staff> Staff { get; set; }

    public virtual DbSet<Wishlist> Wishlists { get; set; }

    public virtual DbSet<WishlistItem> WishlistItems { get; set; }

    public virtual DbSet<WishlistNotification> WishlistNotifications { get; set; }

    public virtual DbSet<WishlistShare> WishlistShares { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        base.OnModelCreating(modelBuilder);
        modelBuilder.ApplyConfiguration(new Configurations.AuditLogConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.BrandConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.CartConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.CartItemConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.CategoryConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.CustomerConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.CustomerAddressConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.OrderConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.OrderItemConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.OrderStatusConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.OrderStatusHistoryConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.PaymentMethodConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.PaymentStatusConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.PermissionConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.ProductConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.ProductAttributeConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.ProductBundleConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.ProductBundleItemConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.ProductImageConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.ProductVariantConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.ProductVariantAttributeConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.RelatedProductConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.ReviewConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.RoleConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.ShippingMethodConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.StaffConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.WishlistConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.WishlistItemConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.WishlistNotificationConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.WishlistShareConfiguration());

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);

public DbSet<ECommerce.Beganit.AdminPanel.ViewModels.StaffViewModelBase> StaffViewModelBase { get; set; } = default!;
}
